/**
 * Practice item bank — Phase 2 (expanded).
 *
 * 20 items per skill × 9 skills = 180 items total. Hand-authored with signature
 * metadata so the mastery tracker, error-signature log, and session composer
 * work end-to-end. Session composer now filters by `usedIds` so a single session
 * never repeats an itemId; with 20 items per skill any realistic 12–20 item
 * session has ample headroom.
 *
 * Design rules:
 *   - Numbers within grade-3 range (0–1000 for arithmetic, 0–24 h for time)
 *   - Every wrong option is plausible (signature misconception, off-by-one,
 *     partial-computation, or adjacent fact) — never filler
 *   - Signature option is always one of the distractors, not the correct answer
 *   - RTL-safe: questions written in Hebrew; math expressions wrapped at render
 *     time by MathText
 *   - difficulty 1 = easiest … 5 = hardest (within that skill)
 *
 * Layer mix per skill:
 *   - Mostly abstract; pictorial only where a visual genuinely helps (fraction
 *     comparisons, clocks). Phase 3 Opus work will expand pictorial coverage
 *     across more skills.
 */

import type { PracticeItem } from '../types';

// ─── ARITH_SUB_REGROUP_ZERO (subtraction across zeros) ────────────────────────
//
// Signature formula for A00 − (Bh×100 + Bt×10 + Bu):
//   correct = A×100 − (Bh×100 + Bt×10 + Bu)
//   sig     = (A − Bh)×100 + Bt×10 + Bu   ← column-wise "take smaller from larger"

const REGROUP_ZERO: PracticeItem[] = [
  {
    itemId:        'P_REGROUP_500_173',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 500 − 173?',
    options:       [327, 473, 337, 427],
    correct:       327,
    signature:     473,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_REGROUP_400_156',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 400 − 156?',
    options:       [244, 254, 344, 356],
    correct:       244,
    signature:     356,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_REGROUP_600_245',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 600 − 245?',
    options:       [355, 445, 365, 455],
    correct:       355,
    signature:     445,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_REGROUP_200_89',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 200 − 89?',
    options:       [111, 121, 289, 211],
    correct:       111,
    signature:     289,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_REGROUP_802_447',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 802 − 447?',
    options:       [355, 445, 365, 455],
    correct:       355,
    signature:     445,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_REGROUP_300_147',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 300 − 147?',
    options:       [153, 247, 163, 253],
    correct:       153,
    signature:     247,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_REGROUP_700_382',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 700 − 382?',
    options:       [318, 482, 328, 418],
    correct:       318,
    signature:     482,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_REGROUP_900_567',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 900 − 567?',
    options:       [333, 467, 343, 433],
    correct:       333,
    signature:     467,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_REGROUP_500_278',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 500 − 278?',
    options:       [222, 378, 232, 322],
    correct:       222,
    signature:     378,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_REGROUP_600_247',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 600 − 247?',
    options:       [353, 447, 363, 453],
    correct:       353,
    signature:     447,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_REGROUP_800_293',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 800 − 293?',
    options:       [507, 693, 517, 607],
    correct:       507,
    signature:     693,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_REGROUP_200_67',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 200 − 67?',
    options:       [133, 267, 143, 233],
    correct:       133,
    signature:     267,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_REGROUP_300_85',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 300 − 85?',
    options:       [215, 385, 225, 315],
    correct:       215,
    signature:     385,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_REGROUP_400_173',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 400 − 173?',
    options:       [227, 373, 237, 327],
    correct:       227,
    signature:     373,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_REGROUP_600_183',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 600 − 183?',
    options:       [417, 583, 427, 517],
    correct:       417,
    signature:     583,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_REGROUP_900_436',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 900 − 436?',
    options:       [464, 536, 474, 564],
    correct:       464,
    signature:     536,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_REGROUP_800_129',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 800 − 129?',
    options:       [671, 729, 681, 771],
    correct:       671,
    signature:     729,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_REGROUP_500_286',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 500 − 286?',
    options:       [214, 386, 224, 314],
    correct:       214,
    signature:     386,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_REGROUP_700_463',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 700 − 463?',
    options:       [237, 363, 247, 337],
    correct:       237,
    signature:     363,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_REGROUP_900_271',
    skillCode:     'ARITH_SUB_REGROUP_ZERO',
    skillHebrewKey:'skill.ARITH_SUB_REGROUP_ZERO',
    question:      'כמה זה 900 − 271?',
    options:       [629, 771, 639, 729],
    correct:       629,
    signature:     771,
    signatureCode: 'ERR_REGROUP_ZERO',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
];

// ─── ARITH_MULT_6_9 (multiplication facts 6×–9×) ──────────────────────────────
//
// No single signature — any wrong product counts as ERR_MULT_FACT. Distractors
// are neighbouring facts (off by one factor), the transposed fact, or a
// near-looking product (e.g. 42 ↔ 48 ↔ 49).

const MULT_6_9: PracticeItem[] = [
  {
    itemId:        'P_MULT_6X7',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 6 × 7?',
    options:       [42, 36, 48, 49],
    correct:       42,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_MULT_7X9',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 7 × 9?',
    options:       [63, 56, 72, 54],
    correct:       63,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_MULT_8X6',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 8 × 6?',
    options:       [48, 42, 54, 56],
    correct:       48,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_MULT_9X9',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 9 × 9?',
    options:       [81, 72, 99, 89],
    correct:       81,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_MULT_6X6',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 6 × 6?',
    options:       [36, 42, 30, 48],
    correct:       36,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_MULT_7X7',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 7 × 7?',
    options:       [49, 42, 56, 47],
    correct:       49,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_MULT_6X8',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 6 × 8?',
    options:       [48, 42, 54, 56],
    correct:       48,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_MULT_6X9',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 6 × 9?',
    options:       [54, 48, 63, 56],
    correct:       54,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_MULT_7X6',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 7 × 6?',
    options:       [42, 36, 48, 49],
    correct:       42,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_MULT_7X8',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 7 × 8?',
    options:       [56, 49, 63, 48],
    correct:       56,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_MULT_8X7',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 8 × 7?',
    options:       [56, 48, 64, 54],
    correct:       56,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_MULT_8X8',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 8 × 8?',
    options:       [64, 56, 72, 63],
    correct:       64,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_MULT_8X9',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 8 × 9?',
    options:       [72, 63, 81, 64],
    correct:       72,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_MULT_9X6',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 9 × 6?',
    options:       [54, 63, 45, 48],
    correct:       54,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_MULT_9X7',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 9 × 7?',
    options:       [63, 54, 72, 56],
    correct:       63,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_MULT_9X8',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'כמה זה 9 × 8?',
    options:       [72, 81, 63, 64],
    correct:       72,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_MULT_MISS_X7_63',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'מה המספר החסר: __ × 7 = 63?',
    options:       [9, 7, 8, 6],
    correct:       9,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_MULT_MISS_8X_48',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'מה המספר החסר: 8 × __ = 48?',
    options:       [6, 8, 7, 9],
    correct:       6,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_MULT_MISS_6X_54',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'מה המספר החסר: 6 × __ = 54?',
    options:       [9, 8, 6, 7],
    correct:       9,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_MULT_MISS_X9_63',
    skillCode:     'ARITH_MULT_6_9',
    skillHebrewKey:'skill.ARITH_MULT_6_9',
    question:      'מה המספר החסר: __ × 9 = 63?',
    options:       [7, 9, 6, 8],
    correct:       7,
    signature:     null,
    signatureCode: 'ERR_MULT_FACT',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
];

// ─── FRAC_COMPARE_UNIT (unit-fraction comparison) ─────────────────────────────
//
// Signature = the fraction with the LARGER denominator (= smaller piece),
// i.e. the child reads the denominator as magnitude.

const FRAC_COMPARE: PracticeItem[] = [
  {
    itemId:        'P_FRAC_HALF_FOURTH',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['½', '¼', 'שווים', 'אי אפשר לדעת'],
    correct:       '½',
    signature:     '¼',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 2, labelA: '½', partsB: 4, labelB: '¼' },
    cpaLayer:      'pictorial',
    difficulty:    1,
  },
  {
    itemId:        'P_FRAC_THIRD_FIFTH',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['⅓', '⅕', 'שווים', 'אי אפשר לדעת'],
    correct:       '⅓',
    signature:     '⅕',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 3, labelA: '⅓', partsB: 5, labelB: '⅕' },
    cpaLayer:      'pictorial',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_FOURTH_EIGHTH',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['¼', '⅛', 'שווים', 'אי אפשר לדעת'],
    correct:       '¼',
    signature:     '⅛',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 4, labelA: '¼', partsB: 8, labelB: '⅛' },
    cpaLayer:      'pictorial',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_HALF_THIRD_NOVIS',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['½', '⅓', 'שווים', 'אי אפשר לדעת'],
    correct:       '½',
    signature:     '⅓',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_HALF_FIFTH_PIC',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['½', '⅕', 'שווים', 'אי אפשר לדעת'],
    correct:       '½',
    signature:     '⅕',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 2, labelA: '½', partsB: 5, labelB: '⅕' },
    cpaLayer:      'pictorial',
    difficulty:    1,
  },
  {
    itemId:        'P_FRAC_HALF_SIXTH_PIC',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['½', '⅙', 'שווים', 'אי אפשר לדעת'],
    correct:       '½',
    signature:     '⅙',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 2, labelA: '½', partsB: 6, labelB: '⅙' },
    cpaLayer:      'pictorial',
    difficulty:    1,
  },
  {
    itemId:        'P_FRAC_THIRD_FOURTH_PIC',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['⅓', '¼', 'שווים', 'אי אפשר לדעת'],
    correct:       '⅓',
    signature:     '¼',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 3, labelA: '⅓', partsB: 4, labelB: '¼' },
    cpaLayer:      'pictorial',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_THIRD_SIXTH_PIC',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['⅓', '⅙', 'שווים', 'אי אפשר לדעת'],
    correct:       '⅓',
    signature:     '⅙',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 3, labelA: '⅓', partsB: 6, labelB: '⅙' },
    cpaLayer:      'pictorial',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_FOURTH_FIFTH_PIC',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['¼', '⅕', 'שווים', 'אי אפשר לדעת'],
    correct:       '¼',
    signature:     '⅕',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 4, labelA: '¼', partsB: 5, labelB: '⅕' },
    cpaLayer:      'pictorial',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_FOURTH_SIXTH_PIC',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['¼', '⅙', 'שווים', 'אי אפשר לדעת'],
    correct:       '¼',
    signature:     '⅙',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 4, labelA: '¼', partsB: 6, labelB: '⅙' },
    cpaLayer:      'pictorial',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_FIFTH_EIGHTH_PIC',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['⅕', '⅛', 'שווים', 'אי אפשר לדעת'],
    correct:       '⅕',
    signature:     '⅛',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 5, labelA: '⅕', partsB: 8, labelB: '⅛' },
    cpaLayer:      'pictorial',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_THIRD_EIGHTH_PIC',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר?',
    options:       ['⅓', '⅛', 'שווים', 'אי אפשר לדעת'],
    correct:       '⅓',
    signature:     '⅛',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        { type: 'fraction_circles', partsA: 3, labelA: '⅓', partsB: 8, labelB: '⅛' },
    cpaLayer:      'pictorial',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_HALF_EIGHTH_ABS',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר: ½ או ⅛?',
    options:       ['½', '⅛', 'שווים', 'אי אפשר לדעת'],
    correct:       '½',
    signature:     '⅛',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_HALF_TENTH_ABS',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר: ½ או 1/10?',
    options:       ['½', '1/10', 'שווים', 'אי אפשר לדעת'],
    correct:       '½',
    signature:     '1/10',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_THIRD_TENTH_ABS',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר: ⅓ או 1/10?',
    options:       ['⅓', '1/10', 'שווים', 'אי אפשר לדעת'],
    correct:       '⅓',
    signature:     '1/10',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_FOURTH_EIGHTH_ABS',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר: ¼ או ⅛?',
    options:       ['¼', '⅛', 'שווים', 'אי אפשר לדעת'],
    correct:       '¼',
    signature:     '⅛',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_FOURTH_TENTH_ABS',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר: ¼ או 1/10?',
    options:       ['¼', '1/10', 'שווים', 'אי אפשר לדעת'],
    correct:       '¼',
    signature:     '1/10',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_FIFTH_SIXTH_ABS',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר: ⅕ או ⅙?',
    options:       ['⅕', '⅙', 'שווים', 'אי אפשר לדעת'],
    correct:       '⅕',
    signature:     '⅙',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_FRAC_SIXTH_EIGHTH_ABS',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר: ⅙ או ⅛?',
    options:       ['⅙', '⅛', 'שווים', 'אי אפשר לדעת'],
    correct:       '⅙',
    signature:     '⅛',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_FRAC_FIFTH_TENTH_ABS',
    skillCode:     'FRAC_COMPARE_UNIT',
    skillHebrewKey:'skill.FRAC_COMPARE_UNIT',
    question:      'איזה שבר גדול יותר: ⅕ או 1/10?',
    options:       ['⅕', '1/10', 'שווים', 'אי אפשר לדעת'],
    correct:       '⅕',
    signature:     '1/10',
    signatureCode: 'ERR_FRACTION_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
];

// ─── FRAC_OF_QUANTITY (a fraction of a whole) ─────────────────────────────────
//
// Signature: N × d (multiply instead of divide). Other distractors include the
// denominator itself and a half/third-of-N false lead.

const FRAC_OF_QTY: PracticeItem[] = [
  {
    itemId:        'P_FRAC_QTY_HALF_OF_10',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה חצי מ-10?',
    options:       [5, 20, 2, 12],
    correct:       5,
    signature:     20,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_FRAC_QTY_THIRD_OF_12',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה שליש מ-12?',
    options:       [4, 36, 3, 9],
    correct:       4,
    signature:     36,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_QTY_QUARTER_OF_16',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה רבע מ-16?',
    options:       [4, 64, 8, 12],
    correct:       4,
    signature:     64,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_QTY_HALF_OF_24',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה חצי מ-24?',
    options:       [12, 48, 6, 22],
    correct:       12,
    signature:     48,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_QTY_THIRD_OF_18',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה שליש מ-18?',
    options:       [6, 54, 9, 3],
    correct:       6,
    signature:     54,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_QTY_QUARTER_OF_20',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה רבע מ-20?',
    options:       [5, 80, 10, 4],
    correct:       5,
    signature:     80,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_QTY_THIRD_OF_15',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה שליש מ-15?',
    options:       [5, 45, 3, 8],
    correct:       5,
    signature:     45,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_QTY_HALF_OF_18',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה חצי מ-18?',
    options:       [9, 36, 6, 12],
    correct:       9,
    signature:     36,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_FRAC_QTY_QUARTER_OF_12',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה רבע מ-12?',
    options:       [3, 48, 4, 6],
    correct:       3,
    signature:     48,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_QTY_FIFTH_OF_15',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה חמישית מ-15?',
    options:       [3, 75, 5, 10],
    correct:       3,
    signature:     75,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_QTY_FIFTH_OF_20',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה חמישית מ-20?',
    options:       [4, 100, 5, 10],
    correct:       4,
    signature:     100,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_QTY_THIRD_OF_21',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה שליש מ-21?',
    options:       [7, 63, 3, 14],
    correct:       7,
    signature:     63,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_QTY_QUARTER_OF_24',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה רבע מ-24?',
    options:       [6, 96, 12, 4],
    correct:       6,
    signature:     96,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_QTY_HALF_OF_30',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה חצי מ-30?',
    options:       [15, 60, 10, 20],
    correct:       15,
    signature:     60,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_FRAC_QTY_FIFTH_OF_25',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה חמישית מ-25?',
    options:       [5, 125, 10, 25],
    correct:       5,
    signature:     125,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_QTY_THIRD_OF_24',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה שליש מ-24?',
    options:       [8, 72, 12, 3],
    correct:       8,
    signature:     72,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_FRAC_QTY_QUARTER_OF_28',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה רבע מ-28?',
    options:       [7, 112, 14, 4],
    correct:       7,
    signature:     112,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_FRAC_QTY_SIXTH_OF_12',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה שישית מ-12?',
    options:       [2, 72, 6, 3],
    correct:       2,
    signature:     72,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_FRAC_QTY_SIXTH_OF_18',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה שישית מ-18?',
    options:       [3, 108, 6, 9],
    correct:       3,
    signature:     108,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_FRAC_QTY_THIRD_OF_30',
    skillCode:     'FRAC_OF_QUANTITY',
    skillHebrewKey:'skill.FRAC_OF_QUANTITY',
    question:      'כמה זה שליש מ-30?',
    options:       [10, 90, 15, 3],
    correct:       10,
    signature:     90,
    signatureCode: 'ERR_FRAC_QUANTITY_BIAS',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
];

// ─── ARITH_WORD_2STEP (2-step word problems) ──────────────────────────────────
//
// Shape: start + add − sub (or the reverse). Signature = add every number
// without regard for operation (ERR_NUMBER_GRAB).

const WORD_2STEP: PracticeItem[] = [
  {
    itemId:        'P_WORD_LEAH_STAMPS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לליאה היו 18 בולים. היא נתנה לחברה 7 בולים, ואז קנתה עוד 4. כמה בולים יש לה עכשיו?',
    options:       [15, 29, 21, 11],
    correct:       15,
    signature:     29,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_WORD_SHIRA_BOOKS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'בכיתה יש 24 ספרים. המורה הוציאה 9 ספרים, ואז הביאה 6 חדשים. כמה ספרים יש עכשיו בכיתה?',
    options:       [21, 39, 27, 15],
    correct:       21,
    signature:     39,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_WORD_ORI_MARBLES',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לאורי יש 30 גולות. הוא נתן לאחיו 12, ואז קיבל מסבא 5 גולות. כמה גולות יש לו?',
    options:       [23, 47, 18, 35],
    correct:       23,
    signature:     47,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_WORD_BAKERY',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'במאפיה אפו 40 לחמניות. מכרו 17, ואז אפו עוד 10. כמה לחמניות יש עכשיו?',
    options:       [33, 67, 23, 43],
    correct:       33,
    signature:     67,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD_DINA_PENCILS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לדינה יש 25 עפרונות. היא נתנה לאחיה 8 עפרונות ואחר כך קיבלה מהמורה 6. כמה עפרונות יש לה?',
    options:       [23, 39, 33, 17],
    correct:       23,
    signature:     39,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_WORD_STORE_APPLES',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'בחנות יש 50 תפוחים. נמכרו 18, ואחר כך הגיעו עוד 12. כמה תפוחים יש עכשיו?',
    options:       [44, 80, 32, 62],
    correct:       44,
    signature:     80,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD_TOM_CARDS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לתום יש 36 כרטיסי כדורגל. הוא החליף 11 עם חבר ואז קנה עוד 7. כמה כרטיסים יש לו?',
    options:       [32, 54, 25, 43],
    correct:       32,
    signature:     54,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_WORD_GARDEN_FLOWERS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'בגינה יש 45 פרחים. קטפו 16, ואז נטעו עוד 9. כמה פרחים יש בגינה?',
    options:       [38, 70, 29, 54],
    correct:       38,
    signature:     70,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD_RONIT_BOOKS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לרונית יש 22 ספרים. היא השאילה 7 לחברה, ואחר כך קנתה 4 חדשים. כמה ספרים יש לה?',
    options:       [19, 33, 15, 26],
    correct:       19,
    signature:     33,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_WORD_CLASS_CHAIRS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'בכיתה יש 32 כיסאות. הוציאו 8 כיסאות לחדר אחר, ואז הביאו 5 חדשים. כמה כיסאות יש?',
    options:       [29, 45, 24, 37],
    correct:       29,
    signature:     45,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_WORD_AVI_COINS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לאבי יש 28 מטבעות. הוא הוציא 10 לקנות ממתקים, ואחר כך מצא 6 מטבעות. כמה מטבעות יש לו?',
    options:       [24, 44, 18, 34],
    correct:       24,
    signature:     44,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_WORD_LIBRARY_BOOKS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'בספרייה יש 60 ספרים. 23 הושאלו ואז הוחזרו 15. כמה ספרים יש בספרייה?',
    options:       [52, 98, 37, 75],
    correct:       52,
    signature:     98,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD_GALI_CARDS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לגלי יש 15 גלויות. היא שלחה 4 לחברות, ואז קיבלה 8 בדואר. כמה גלויות יש לה?',
    options:       [19, 27, 11, 23],
    correct:       19,
    signature:     27,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_WORD_PARK_TREES',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'בפארק יש 70 עצים. כרתו 25 עצים ישנים, ואז נטעו 18 חדשים. כמה עצים יש בפארק?',
    options:       [63, 113, 45, 88],
    correct:       63,
    signature:     113,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD_NOAM_BALLS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לנועם יש 34 כדורים. הוא איבד 9 ואחר כך קיבל 5 מחבר. כמה כדורים יש לו?',
    options:       [30, 48, 25, 39],
    correct:       30,
    signature:     48,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_WORD_STORE_BOXES',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'במחסן יש 55 קופסאות. לקחו 20 קופסאות ואז הביאו עוד 14. כמה קופסאות יש במחסן?',
    options:       [49, 89, 35, 69],
    correct:       49,
    signature:     89,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD_RACHEL_TOMATOES',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לרחל יש 18 עגבניות. 6 נרקבו ואחר כך היא קטפה 4 חדשות. כמה עגבניות יש לה?',
    options:       [16, 28, 12, 22],
    correct:       16,
    signature:     28,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_WORD_AYAR_LEGO',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לאייר יש 40 חלקי לגו. הוא נתן לאחיו 13 ואחר כך קנה 7 חדשים. כמה חלקים יש לו?',
    options:       [34, 60, 27, 47],
    correct:       34,
    signature:     60,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_WORD_SCHOOL_BALLS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'בבית הספר יש 48 כדורי כדורסל. 16 אבדו ואחר כך נמצאו 9. כמה כדורים יש?',
    options:       [41, 73, 32, 57],
    correct:       41,
    signature:     73,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD_DAVIR_CARDS',
    skillCode:     'ARITH_WORD_2STEP',
    skillHebrewKey:'skill.ARITH_WORD_2STEP',
    question:      'לדביר יש 26 קלפים. הוא נתן 8 לחבר ואחר כך קיבל 3 חדשים. כמה קלפים יש לו?',
    options:       [21, 37, 18, 29],
    correct:       21,
    signature:     37,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
];

// ─── ARITH_WORD_3STEP (3-step word problems) ─────────────────────────────────
//
// Items 1–7 = 3 sequential operations on 4 values (simple add/subtract chains).
// Items 8–20 = multiplication built in as one of the steps.
// Signature: add every number in the problem (ERR_NUMBER_GRAB).

const WORD_3STEP: PracticeItem[] = [
  {
    itemId:        'P_WORD3_CANDIES',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'בכיתה יש 28 ילדים. 12 הלכו לטיול ואחר כך חזרו 5. כמה ילדים בכיתה עכשיו?',
    options:       [21, 45, 33, 11],
    correct:       21,
    signature:     45,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD3_STICKERS',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'לנועה יש 40 מדבקות. היא קנתה עוד 8 וחילקה לשלוש חברות 15 מדבקות. כמה נשארו לה?',
    options:       [33, 63, 17, 48],
    correct:       33,
    signature:     63,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_RONI_COINS',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'לרוני יש 25 מטבעות. הוא קיבל מאביו 10, נתן לאחיו 8 ואחר כך מצא עוד 4. כמה מטבעות יש לו?',
    options:       [31, 47, 27, 35],
    correct:       31,
    signature:     47,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD3_SOCCER_FIELD',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'במגרש יש 18 ילדים. הגיעו עוד 7, אחר כך 3 הלכו הביתה ובסוף הגיעו 5 נוספים. כמה ילדים יש עכשיו?',
    options:       [27, 33, 22, 30],
    correct:       27,
    signature:     33,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD3_GAL_SHEKELS',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'לגל היו 60 שקלים. היא קנתה ספר ב-22, אחר כך קיבלה 15 מסבתא ואחר כך הוציאה 8 על גלידה. כמה שקלים נשארו?',
    options:       [45, 105, 53, 38],
    correct:       45,
    signature:     105,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD3_ORANGES',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'בבית יש 45 תפוזים. אכלו 12, קנו עוד 20 ואחר כך נתנו 15 לשכנים. כמה תפוזים יש?',
    options:       [38, 92, 53, 33],
    correct:       38,
    signature:     92,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD3_ORA_PAINTINGS',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'לאורה יש 30 ציורים. היא ציירה עוד 6, מכרה 11 בתערוכה ואז ציירה עוד 4. כמה ציורים יש לה?',
    options:       [29, 51, 25, 36],
    correct:       29,
    signature:     51,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_WORD3_PENCILS_PER_KID',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'לכל ילד יש 6 עפרונות. 4 ילדים ישבו יחד ואחר כך 3 עפרונות נשברו. כמה עפרונות תקינים נשארו?',
    options:       [21, 13, 24, 18],
    correct:       21,
    signature:     13,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_APPLE_BAGS',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'אמא קנתה 3 שקיות. בכל שקית 8 תפוחים. היא נתנה לשכנה 5 תפוחים. כמה תפוחים נשארו?',
    options:       [19, 16, 24, 14],
    correct:       19,
    signature:     16,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_CLASS_ROWS',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'בכיתה יש 5 שורות. בכל שורה 6 כיסאות. 4 תלמידים חסרים היום. כמה מקומות תפוסים?',
    options:       [26, 15, 30, 22],
    correct:       26,
    signature:     15,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_CHOCOLATE_BOXES',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'לינה קנתה 4 קופסאות שוקולד. בכל קופסה 9 שוקולדים. היא כבר אכלה 10. כמה שוקולדים נשארו?',
    options:       [26, 23, 36, 16],
    correct:       26,
    signature:     23,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_MILK_COWS',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'בחווה יש 5 פרות. כל פרה נותנת 8 ליטר חלב. כבר נשפכו 4 ליטרים. כמה ליטר נשארו?',
    options:       [36, 17, 40, 32],
    correct:       36,
    signature:     17,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_CLASSES_CANDY',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      "כיתה א' קנתה 6 שקיות סוכריות, בכל שקית 7 סוכריות. כיתה ב' קנתה 20 סוכריות. כמה סוכריות יש בסך הכול?",
    options:       [62, 33, 42, 47],
    correct:       62,
    signature:     33,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_SHACHAR_LINES',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'לשחר יש 3 דפים. בכל דף הוא כתב 8 שורות. הוא מחק 7 שורות. כמה שורות יש לו?',
    options:       [17, 18, 24, 10],
    correct:       17,
    signature:     18,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_SHELF_BOOKS',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'בחנות יש 4 מדפים. בכל מדף 9 ספרים. נמכרו 16 ספרים. כמה נשארו?',
    options:       [20, 29, 36, 12],
    correct:       20,
    signature:     29,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_DANA_CARDS',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'לדנה יש 5 קופסאות כרטיסים. בכל קופסה 8 כרטיסים. היא קיבלה עוד 7 כרטיסים מחבר. כמה כרטיסים יש לה?',
    options:       [47, 20, 40, 35],
    correct:       47,
    signature:     20,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_TREE_ROWS',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'בגינה יש 6 שורות של עצים. בכל שורה 7 עצים. נטעו עוד 5 עצים. כמה עצים יש בגינה?',
    options:       [47, 18, 42, 52],
    correct:       47,
    signature:     18,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_MIA_CHANGE',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'מיה קנתה 4 פרחים ב-7 שקלים כל אחד. היא שילמה 50 שקלים. כמה עודף קיבלה?',
    options:       [22, 39, 28, 46],
    correct:       22,
    signature:     39,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    5,
  },
  {
    itemId:        'P_WORD3_LIBRARY_SHELVES',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      'בספרייה יש 8 מדפים. על כל מדף 9 ספרים. 15 ספרים הושאלו. כמה ספרים נשארו?',
    options:       [57, 32, 72, 42],
    correct:       57,
    signature:     32,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_WORD3_KIDS_PRESENT',
    skillCode:     'ARITH_WORD_3STEP',
    skillHebrewKey:'skill.ARITH_WORD_3STEP',
    question:      "לכיתה ג' יש 5 שורות. בכל שורה 7 ילדים. 3 ילדים חסרים היום. כמה ילדים נוכחים?",
    options:       [32, 15, 35, 25],
    correct:       32,
    signature:     15,
    signatureCode: 'ERR_NUMBER_GRAB',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
];

// ─── MEAS_UNIT_CONVERT_CM (m ↔ cm) ────────────────────────────────────────────
//
// Signature: raw addition of the two numbers (forgets 1 m = 100 cm).

const UNIT_CONVERT_CM: PracticeItem[] = [
  {
    itemId:        'P_UNIT_1M50CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-1 מטר ו-50 סנטימטרים?',
    options:       [150, 51, 1050, 105],
    correct:       150,
    signature:     51,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_UNIT_3M20CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-3 מטרים ו-20 סנטימטרים?',
    options:       [320, 23, 3020, 302],
    correct:       320,
    signature:     23,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_UNIT_4M5CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-4 מטרים ו-5 סנטימטרים?',
    options:       [405, 9, 4050, 450],
    correct:       405,
    signature:     9,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_UNIT_2M75CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-2 מטרים ו-75 סנטימטרים?',
    options:       [275, 77, 2075, 257],
    correct:       275,
    signature:     77,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_UNIT_2M30CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-2 מטרים ו-30 סנטימטרים?',
    options:       [230, 32, 2030, 203],
    correct:       230,
    signature:     32,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_UNIT_5M_ONLY',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-5 מטרים?',
    options:       [500, 5, 5000, 50],
    correct:       500,
    signature:     5,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_UNIT_1M80CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-1 מטר ו-80 סנטימטרים?',
    options:       [180, 81, 1080, 108],
    correct:       180,
    signature:     81,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_UNIT_3M45CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-3 מטרים ו-45 סנטימטרים?',
    options:       [345, 48, 3045, 304],
    correct:       345,
    signature:     48,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_UNIT_6M10CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-6 מטרים ו-10 סנטימטרים?',
    options:       [610, 16, 6010, 601],
    correct:       610,
    signature:     16,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_UNIT_2M60CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-2 מטרים ו-60 סנטימטרים?',
    options:       [260, 62, 2060, 206],
    correct:       260,
    signature:     62,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_UNIT_4M25CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-4 מטרים ו-25 סנטימטרים?',
    options:       [425, 29, 4025, 402],
    correct:       425,
    signature:     29,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_UNIT_5M90CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-5 מטרים ו-90 סנטימטרים?',
    options:       [590, 95, 5090, 509],
    correct:       590,
    signature:     95,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_UNIT_7M_ONLY',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-7 מטרים?',
    options:       [700, 7, 7000, 70],
    correct:       700,
    signature:     7,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_UNIT_3M60CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-3 מטרים ו-60 סנטימטרים?',
    options:       [360, 63, 3060, 306],
    correct:       360,
    signature:     63,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_UNIT_1M25CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-1 מטר ו-25 סנטימטרים?',
    options:       [125, 26, 1025, 102],
    correct:       125,
    signature:     26,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    1,
  },
  {
    itemId:        'P_UNIT_4M40CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-4 מטרים ו-40 סנטימטרים?',
    options:       [440, 44, 4040, 404],
    correct:       440,
    signature:     44,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_UNIT_6M5CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-6 מטרים ו-5 סנטימטרים?',
    options:       [605, 11, 6050, 650],
    correct:       605,
    signature:     11,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_UNIT_2M15CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-2 מטרים ו-15 סנטימטרים?',
    options:       [215, 17, 2015, 201],
    correct:       215,
    signature:     17,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_UNIT_5M35CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-5 מטרים ו-35 סנטימטרים?',
    options:       [535, 40, 5035, 503],
    correct:       535,
    signature:     40,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_UNIT_3M80CM',
    skillCode:     'MEAS_UNIT_CONVERT_CM',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_CM',
    question:      'כמה סנטימטרים יש ב-3 מטרים ו-80 סנטימטרים?',
    options:       [380, 83, 3080, 308],
    correct:       380,
    signature:     83,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
];

// ─── MEAS_TIME_CROSS_HOUR (time arithmetic crossing the hour) ────────────────
//
// Signature: add minutes without carrying the extra hour (e.g. 2:40 + 30 → 2:70).

const TIME_CROSS: PracticeItem[] = [
  {
    itemId:        'P_TIME_2_40_PLUS_30',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'השיעור מתחיל ב-2:40 ונמשך 30 דקות. מתי הוא נגמר?',
    options:       ['3:10', '2:70', '3:70', '2:10'],
    correct:       '3:10',
    signature:     '2:70',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        { type: 'analog_clock', time: '2:40' },
    cpaLayer:      'pictorial',
    difficulty:    1,
  },
  {
    itemId:        'P_TIME_4_50_PLUS_20',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'הארוחה מתחילה ב-4:50 ונמשכת 20 דקות. מתי היא נגמרת?',
    options:       ['5:10', '4:70', '5:70', '4:30'],
    correct:       '5:10',
    signature:     '4:70',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        { type: 'analog_clock', time: '4:50' },
    cpaLayer:      'pictorial',
    difficulty:    1,
  },
  {
    itemId:        'P_TIME_1_35_PLUS_50',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'הטיול מתחיל ב-1:35 ונמשך 50 דקות. מתי הוא נגמר?',
    options:       ['2:25', '1:85', '2:85', '1:25'],
    correct:       '2:25',
    signature:     '1:85',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_3_55_PLUS_15',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'הסרטון מתחיל ב-3:55 ונמשך 15 דקות. מתי הוא נגמר?',
    options:       ['4:10', '3:70', '4:70', '3:40'],
    correct:       '4:10',
    signature:     '3:70',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_5_45_PLUS_25',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'המשחק מתחיל ב-5:45 ונמשך 25 דקות. מתי הוא נגמר?',
    options:       ['6:10', '5:70', '6:15', '5:45'],
    correct:       '6:10',
    signature:     '5:70',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        { type: 'analog_clock', time: '5:45' },
    cpaLayer:      'pictorial',
    difficulty:    1,
  },
  {
    itemId:        'P_TIME_7_50_PLUS_30',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'השיעור מתחיל ב-7:50 ונמשך 30 דקות. מתי הוא נגמר?',
    options:       ['8:20', '7:80', '8:25', '7:20'],
    correct:       '8:20',
    signature:     '7:80',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        { type: 'analog_clock', time: '7:50' },
    cpaLayer:      'pictorial',
    difficulty:    1,
  },
  {
    itemId:        'P_TIME_10_40_PLUS_35',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'ההצגה מתחילה ב-10:40 ונמשכת 35 דקות. מתי היא נגמרת?',
    options:       ['11:15', '10:75', '11:20', '10:15'],
    correct:       '11:15',
    signature:     '10:75',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        { type: 'analog_clock', time: '10:40' },
    cpaLayer:      'pictorial',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_8_55_PLUS_10',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'ההפסקה מתחילה ב-8:55 ונמשכת 10 דקות. מתי היא נגמרת?',
    options:       ['9:05', '8:65', '9:10', '8:05'],
    correct:       '9:05',
    signature:     '8:65',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        { type: 'analog_clock', time: '8:55' },
    cpaLayer:      'pictorial',
    difficulty:    1,
  },
  {
    itemId:        'P_TIME_6_30_PLUS_45',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'האימון מתחיל ב-6:30 ונמשך 45 דקות. מתי הוא נגמר?',
    options:       ['7:15', '6:75', '7:20', '6:15'],
    correct:       '7:15',
    signature:     '6:75',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        { type: 'analog_clock', time: '6:30' },
    cpaLayer:      'pictorial',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_9_45_PLUS_25',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'המסיבה מתחילה ב-9:45 ונמשכת 25 דקות. מתי היא נגמרת?',
    options:       ['10:10', '9:70', '10:15', '9:10'],
    correct:       '10:10',
    signature:     '9:70',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_11_50_PLUS_20',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'הסרט מתחיל ב-11:50 ונמשך 20 דקות. מתי הוא נגמר?',
    options:       ['12:10', '11:70', '12:15', '11:10'],
    correct:       '12:10',
    signature:     '11:70',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_TIME_3_35_PLUS_40',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'הטיול מתחיל ב-3:35 ונמשך 40 דקות. מתי הוא נגמר?',
    options:       ['4:15', '3:75', '4:20', '3:15'],
    correct:       '4:15',
    signature:     '3:75',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_2_50_PLUS_15',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'הנסיעה מתחילה ב-2:50 ונמשכת 15 דקות. מתי היא נגמרת?',
    options:       ['3:05', '2:65', '3:10', '2:05'],
    correct:       '3:05',
    signature:     '2:65',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_7_40_PLUS_30',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'ההפסקה מתחילה ב-7:40 ונמשכת 30 דקות. מתי היא נגמרת?',
    options:       ['8:10', '7:70', '8:15', '7:10'],
    correct:       '8:10',
    signature:     '7:70',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_5_55_PLUS_10',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'המשחק מתחיל ב-5:55 ונמשך 10 דקות. מתי הוא נגמר?',
    options:       ['6:05', '5:65', '6:10', '5:05'],
    correct:       '6:05',
    signature:     '5:65',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_10_45_PLUS_35',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'השיעור מתחיל ב-10:45 ונמשך 35 דקות. מתי הוא נגמר?',
    options:       ['11:20', '10:80', '11:25', '10:20'],
    correct:       '11:20',
    signature:     '10:80',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_TIME_4_45_PLUS_20',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'האימון מתחיל ב-4:45 ונמשך 20 דקות. מתי הוא נגמר?',
    options:       ['5:05', '4:65', '5:10', '4:05'],
    correct:       '5:05',
    signature:     '4:65',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_9_55_PLUS_30',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'המסיבה מתחילה ב-9:55 ונמשכת 30 דקות. מתי היא נגמרת?',
    options:       ['10:25', '9:85', '10:30', '9:25'],
    correct:       '10:25',
    signature:     '9:85',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_TIME_1_40_PLUS_30',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'ההצגה מתחילה ב-1:40 ונמשכת 30 דקות. מתי היא נגמרת?',
    options:       ['2:10', '1:70', '2:15', '1:10'],
    correct:       '2:10',
    signature:     '1:70',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_TIME_6_50_PLUS_25',
    skillCode:     'MEAS_TIME_CROSS_HOUR',
    skillHebrewKey:'skill.MEAS_TIME_CROSS_HOUR',
    question:      'הפסטיבל מתחיל ב-6:50 ונמשך 25 דקות. מתי הוא נגמר?',
    options:       ['7:15', '6:75', '7:20', '6:15'],
    correct:       '7:15',
    signature:     '6:75',
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
];

// ─── MEAS_UNIT_CONVERT_M (km ↔ m) ─────────────────────────────────────────────
//
// Signature: multiply km by 100 instead of 1000 (kg/cm-scale habit carried over).

const UNIT_CONVERT_M: PracticeItem[] = [
  {
    itemId:        'P_KM_2KM300M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-2 קילומטרים ו-300 מטרים?',
    options:       [2300, 500, 2030, 230],
    correct:       2300,
    signature:     500,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_1KM500M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-1 קילומטר ו-500 מטרים?',
    options:       [1500, 600, 150, 1050],
    correct:       1500,
    signature:     600,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_KM_3KM200M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-3 קילומטרים ו-200 מטרים?',
    options:       [3200, 500, 3020, 320],
    correct:       3200,
    signature:     500,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_4KM600M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-4 קילומטרים ו-600 מטרים?',
    options:       [4600, 1000, 4060, 460],
    correct:       4600,
    signature:     1000,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_2KM750M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-2 קילומטרים ו-750 מטרים?',
    options:       [2750, 950, 2075, 275],
    correct:       2750,
    signature:     950,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_5KM100M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-5 קילומטרים ו-100 מטרים?',
    options:       [5100, 600, 5010, 510],
    correct:       5100,
    signature:     600,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_3KM500M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-3 קילומטרים ו-500 מטרים?',
    options:       [3500, 800, 3050, 350],
    correct:       3500,
    signature:     800,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_1KM250M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-1 קילומטר ו-250 מטרים?',
    options:       [1250, 350, 1025, 125],
    correct:       1250,
    signature:     350,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_KM_7KM_ONLY',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-7 קילומטרים?',
    options:       [7000, 700, 70, 7070],
    correct:       7000,
    signature:     700,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_4KM50M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-4 קילומטרים ו-50 מטרים?',
    options:       [4050, 450, 4500, 405],
    correct:       4050,
    signature:     450,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_KM_6KM400M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-6 קילומטרים ו-400 מטרים?',
    options:       [6400, 1000, 6040, 640],
    correct:       6400,
    signature:     1000,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_2KM80M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-2 קילומטרים ו-80 מטרים?',
    options:       [2080, 280, 2800, 208],
    correct:       2080,
    signature:     280,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_KM_5KM500M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-5 קילומטרים ו-500 מטרים?',
    options:       [5500, 1000, 5050, 550],
    correct:       5500,
    signature:     1000,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_3KM750M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-3 קילומטרים ו-750 מטרים?',
    options:       [3750, 1050, 3075, 375],
    correct:       3750,
    signature:     1050,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_8KM200M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-8 קילומטרים ו-200 מטרים?',
    options:       [8200, 1000, 8020, 820],
    correct:       8200,
    signature:     1000,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_4KM400M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-4 קילומטרים ו-400 מטרים?',
    options:       [4400, 800, 4040, 440],
    correct:       4400,
    signature:     800,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_1KM800M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-1 קילומטר ו-800 מטרים?',
    options:       [1800, 900, 1080, 180],
    correct:       1800,
    signature:     900,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    2,
  },
  {
    itemId:        'P_KM_6KM50M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-6 קילומטרים ו-50 מטרים?',
    options:       [6050, 650, 6500, 605],
    correct:       6050,
    signature:     650,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
  {
    itemId:        'P_KM_9KM300M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-9 קילומטרים ו-300 מטרים?',
    options:       [9300, 1200, 9030, 930],
    correct:       9300,
    signature:     1200,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    3,
  },
  {
    itemId:        'P_KM_3KM30M',
    skillCode:     'MEAS_UNIT_CONVERT_M',
    skillHebrewKey:'skill.MEAS_UNIT_CONVERT_M',
    question:      'כמה מטרים יש ב-3 קילומטרים ו-30 מטרים?',
    options:       [3030, 330, 3300, 303],
    correct:       3030,
    signature:     330,
    signatureCode: 'ERR_UNIT_MISMATCH',
    visual:        null,
    cpaLayer:      'abstract',
    difficulty:    4,
  },
];

// ─── Public export ────────────────────────────────────────────────────────────

export const PRACTICE_ITEMS_BY_SKILL: Record<string, PracticeItem[]> = {
  ARITH_SUB_REGROUP_ZERO: REGROUP_ZERO,
  ARITH_MULT_6_9:         MULT_6_9,
  FRAC_COMPARE_UNIT:      FRAC_COMPARE,
  FRAC_OF_QUANTITY:       FRAC_OF_QTY,
  ARITH_WORD_2STEP:       WORD_2STEP,
  ARITH_WORD_3STEP:       WORD_3STEP,
  MEAS_UNIT_CONVERT_CM:   UNIT_CONVERT_CM,
  MEAS_UNIT_CONVERT_M:    UNIT_CONVERT_M,
  MEAS_TIME_CROSS_HOUR:   TIME_CROSS,
};

export const PRACTICE_ITEM_BY_ID: Record<string, PracticeItem> = Object.fromEntries(
  Object.values(PRACTICE_ITEMS_BY_SKILL).flat().map(it => [it.itemId, it])
);

/** All skill codes that have at least one practice item. */
export const SKILLS_WITH_PRACTICE: string[] = Object.keys(PRACTICE_ITEMS_BY_SKILL);
